const WOMAN_NAMES = [
    'Aleksandra',
    'Alena',
    'Alina',
    'Alisa',
    'Alla',
    'Anastasija',
    'Angelina',
    'Anna',
    'Antonina',
    'Arina',
    'Valentina',
    'Valerija',
    'Varvara',
    'Vasilisa',
    'Vera',
    'Veronika',
    'Viktorija',
    'Galina',
    'Darja',
    'Eva',
    'Evgenija',
    'Evdokija',
    'Ekaterina',
    'Elena',
    'Elizaveta',
    'Zhanna',
    'Zinaida',
    'Zlata',
    'Zoja',
    'Ivanna',
    'Irina',
    'Ija',
    'Kira',
    'Kristina',
    'Ksenija',
    'Lidija',
    'Ljubov',
    'Ljudmila',
    'Margarita',
    'Marina',
    'Marija',
    'Milana',
    'Nadezhda',
    'Natalja',
    'Nina',
    'Olga',
    'Polina',
    'Raisa',
    'Svetlana',
    'Sofija',
    'Taisija',
    'Tamara',
    'Tatjana',
    'Uljana',
    'Julija',
]

const WOMAN_LASTNAMES = [
    'Orlova',
    'Lebedeva',
    'Simonova',
    'Aleksandrova',
    'Tretjakova',
    'Lenskaja',
    'Kamenskih',
    'Kozhevnikova',
    'Denisova',
    'Andreeva',
    'Tolmacheva',
    'Shevchenko',
    'Panchenko',
    'Nazarova',
    'Bezrukova',
    'Sokolova',
    'Rodochinskaja',
    'Volkova',
    'Kovalevskaja',
    'Oblomova',
    'Koroleva',
    'Volochkova',
    'Matveeva',
    'Levchenko',
    'Lionova',
    'Kotova',
    'Bratislavskaja',
    'Poljakova',
    'Efimova',
    'Malysheva',
    'Tarasova',
    'Novitskaja',
    'Novikova',
    'Istomina',
    'Ivleva',
    'Uljanova',
    'Romanova',
    'Gronskaja',
    'Bondarenko',
    'Hovanskaja',
]

const MAN_NAMES = [
    'Artem',
    'Bogdan',
    'Boris',
    'Vadim',
    'Valentin',
    'Valerij',
    'Vasilij',
    'Viktor',
    'Vitalij',
    'Vladimir',
    'Vladislav',
    'Vjacheslav',
    'Gennadij',
    'Georgij',
    'Gleb',
    'Grigorij',
    'Daniil',
    'Denis',
    'Dmitrij',
    'Evgenij',
    'Egor',
    'Ivan',
    'Igor',
    'Ilja',
    'Kirill',
    'Konstantin',
    'Leonid',
    'Makar',
    'Maksim',
    'Mark',
    'Matvej',
    'Mihail',
    'Nikita',
    'Nikolaj',
    'Oleg',
    'Pavel',
    'Petr',
    'Roman',
    'Ruslan',
    'Svjatoslav',
    'Semen',
    'Sergej',
    'Stanislav',
    'Stepan',
    'Timofej',
    'Fedor',
    'Jurij',
    'Jaroslav',
]

const MAN_LASTNAMES = [
    'Smirnov',
    'Ivanov',
    'Kuznetsov',
    'Sokolov',
    'Popov',
    'Lebedev',
    'Kozlov',
    'Novikov',
    'Morozov',
    'Petrov',
    'Volkov',
    'Solovev',
    'Vasilev',
    'Zajtsev',
    'Pavlov',
    'Semenov',
    'Golubev',
    'Vinogradov',
    'Bogdanov',
    'Vorobev',
    'Fedorov',
    'Mihajlov',
    'Beljaev',
    'Tarasov',
    'Belov',
    'Komarov',
    'Orlov',
    'Kiselev',
    'Makarov',
    'Andreev',
    'Kovalev',
    'Ilin',
    'Gusev',
    'Titov',
    'Kuzmin',
    'Kudrjavtsev',
    'Baranov',
    'Kulikov',
    'Alekseev',
    'Stepanov',
    'Jakovlev',
    'Sorokin',
    'Sergeev',
    'Romanov',
    'Zaharov',
    'Borisov',
    'Korolev',
    'Gerasimov',
    'Ponomarev',
    'Grigorev',
    'Lazarev',
    'Medvedev',
    'Ershov',
    'Nikitin',
    'Sobolev',
    'Rjabov',
    'Poljakov',
    'Tsvetkov',
    'Danilov',
    'Zhukov',
    'Frolov',
    'Zhuravlev',
    'Nikolaev',
    'Krylov',
    'Maksimov',
    'Sidorov',
    'Osipov',
    'Belousov',
    'Fedotov',
    'Dorofeev',
    'Egorov',
    'Matveev',
    'Bobrov',
    'Dmitriev',
    'Kalinin',
    'Anisimov',
    'Petuhov',
    'Antonov',
    'Timofeev',
    'Nikiforov',
    'Veselov',
    'Filippov',
    'Markov',
    'Bolshakov',
    'Suhanov',
    'Mironov',
    'Shirjaev',
    'Aleksandrov',
    'Konovalov',
    'Shestakov',
    'Kazakov',
    'Efimov',
    'Denisov',
    'Gromov',
    'Fomin',
    'Davydov'
]

const PHONE_CODES = [
    900,
    901,
    902,
    903,
    904,
    905,
    906,
    908,
    909,
    910,
    911,
    912,
    913,
    914,
    915,
    916,
    917,
    918,
    919,
    920,
    921,
    922,
    923,
    924,
    925,
    926,
    927,
    928,
    929,
    930,
    931,
    932,
    933,
    934,
    936,
    937,
    938,
    939,
    941,
    942,
    950,
    951,
    952,
    953,
    954,
    955,
    956,
    958,
    960,
    961,
    962,
    963,
    964,
    965,
    966,
    967,
    968,
    969,
    970,
    971,
    977,
    978,
    979,
    980,
    981,
    982,
    983,
    984,
    985,
    986,
    987,
    988,
    989,
    990,
    991,
    992,
    993,
    994,
    995,
    996,
    997,
    999,
]

const GROUPS = [
    'CEO',
    'Managers',
    'HR',
    'Teamleads',
    'Developers',
    'Financials',
    'Sales',
    'Unmanaged',
]

const CITIES = [
    'Moscow',
    'Saint-Petersburg',
    'Novosibirsk',
    'Ekaterinburg',
    'Kazan',
    'Nizhniy Novgorod',
    'Krasnoyarsk',
    'Chelyabinsk',
    'Samara',
    'Ufa',
    'Rostov',
    'Omsk',
    'Krasnodar',
    'Voronezh',
    'Perm',
    'Volgograd',
]

const random = (min, max) => (
    Math.floor(Math.random() * (max - min + 1)) + min
)

const gen_fullname = (sex) => {
    let name
    let lastname

    if (sex) {
        name = MAN_NAMES[random(0, MAN_NAMES.length-1)]
        lastname = MAN_LASTNAMES[random(0, MAN_LASTNAMES.length-1)]
    } else {
        name = WOMAN_NAMES[random(0, WOMAN_NAMES.length-1)]
        lastname = WOMAN_LASTNAMES[random(0, WOMAN_LASTNAMES.length-1)]
    }

    return [name, lastname]
}

const gen_phone = () => (
    '+7' + PHONE_CODES[random(0, PHONE_CODES.length-1)].toString() + random(1000000, 9999999).toString()
)

const generateUsers = (number) => {
    const data = {users: {}}
    for (let i = 0; i < number; i++) {
        const id = random(1000000, 9999999)
        const [name, lastname] = gen_fullname(random(0, 1))
        const fullname = name + ' ' + lastname
        const email = `${name.toLowerCase()}_${lastname.toLowerCase()}@somebox.com`
        const phone = gen_phone()
        const group = GROUPS[random(0, GROUPS.length-1)]
        const city = CITIES[random(0, CITIES.length-1)]
        const salary = Math.floor(random(50000, 500000) / 100) * 100
        const image_url = ''
        data.users[id] = {
            'id': id,
            'group': group,
            'fullname': fullname,
            'email': email,
            'phone': phone,
            'salary': salary,
            'city': city,
            'image_url': image_url
        }
    }
    return data
}

module.exports = generateUsers